#     _____                          _____ __
#    / ___/_____________  ___  ____ / ___// /_  ____ _________
#    \__ \/ ___/ ___/ _ \/ _ \/ __ \\__ \/ __ \/ __ `/ ___/ _ \
#   ___/ / /__/ /  /  __/  __/ / / /__/ / / / / /_/ / /  /  __/
#  /____/\___/_/   \___/\___/_/ /_/____/_/ /_/\__,_/_/   \___/
# Fatto con tanto ♥ da ohhhhNess - YumaHisai - Tricolor

Version: '${project.version}'

# Zone
controllo:
   sospetto:
     x:
     y:
     z:
   staffer:
     x:
     y:
     z:
   world: "world"